services:
  db:
    image: postgres:16.10-alpine
    container_name: aibot
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6378:6379"

  redisinsight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data



volumes:
  redisinsight:
  postgres-data:

